package Interfaz;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JOptionPane;
import modelo.beans.Usuario;
import modelo.logic.UsuarioLogic;

/**
 *
 * @author Juan Diaz
 */
public class Consult_User extends javax.swing.JPanel {

    /**
     * Creates new form Consult_User
     */
    public Consult_User() {
        initComponents();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultUser = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbSTitulo1 = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbSTitulo5 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lbSTitulo6 = new javax.swing.JLabel();
        txtCantRetirada = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lbSTitulo7 = new javax.swing.JLabel();
        txtSaldoActual = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lbSTitulo8 = new javax.swing.JLabel();
        txtUltimoAcceso = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnTransacciones = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(640, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultUser.setBackground(new java.awt.Color(12, 33, 193));
        btnConsultUser.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnConsultUser.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultUser.setText("Consulta");
        btnConsultUser.setBorderPainted(false);
        btnConsultUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultUserActionPerformed(evt);
            }
        });
        add(btnConsultUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 130, 30));

        lbTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbTitulo.setText("Consulta de Usuarios");
        add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        lbSTitulo1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo1.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo1.setText("No. Tarjeta");
        add(lbSTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtNumTarjeta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNumTarjeta.setForeground(new java.awt.Color(0, 8, 66));
        txtNumTarjeta.setText("Número de Tarjeta");
        txtNumTarjeta.setBorder(null);
        add(txtNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 480, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator2.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 490, 10));

        lbSTitulo5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo5.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo5.setText("No. Cuenta");
        add(lbSTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        txtNumCuenta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNumCuenta.setForeground(new java.awt.Color(0, 8, 66));
        txtNumCuenta.setText("Número de Cuenta");
        txtNumCuenta.setBorder(null);
        add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 490, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator6.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 490, 10));

        lbSTitulo6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo6.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo6.setText("Cantidad Retirada");
        add(lbSTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        txtCantRetirada.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtCantRetirada.setForeground(new java.awt.Color(0, 8, 66));
        txtCantRetirada.setText("Cantidad Retirada");
        txtCantRetirada.setBorder(null);
        add(txtCantRetirada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 490, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator7.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 490, 10));

        lbSTitulo7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo7.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo7.setText("Saldo Actual");
        add(lbSTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        txtSaldoActual.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtSaldoActual.setForeground(new java.awt.Color(0, 8, 66));
        txtSaldoActual.setText("Saldo Actual");
        txtSaldoActual.setBorder(null);
        add(txtSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 490, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator8.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 490, 10));

        lbSTitulo8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo8.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo8.setText("Último Acceso");
        add(lbSTitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        txtUltimoAcceso.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtUltimoAcceso.setForeground(new java.awt.Color(0, 8, 66));
        txtUltimoAcceso.setText("Último Acceso");
        txtUltimoAcceso.setBorder(null);
        add(txtUltimoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 490, 30));

        jSeparator9.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator9.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 490, 10));

        btnTransacciones.setBackground(new java.awt.Color(12, 33, 193));
        btnTransacciones.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnTransacciones.setForeground(new java.awt.Color(255, 255, 255));
        btnTransacciones.setText("Transacciones");
        btnTransacciones.setBorderPainted(false);
        btnTransacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionesActionPerformed(evt);
            }
        });
        add(btnTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultUserActionPerformed
        buscarUsuario();
    }//GEN-LAST:event_btnConsultUserActionPerformed

    private void btnTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionesActionPerformed
        // TODO add your handling code here:
        Transacciones_User tabla = new Transacciones_User(UsuarioLogic.obtener(txtNumTarjeta.getText()));
        tabla.setDefaultCloseOperation(Transacciones_User.DISPOSE_ON_CLOSE);
        tabla.setVisible(true);
    }//GEN-LAST:event_btnTransaccionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultUser;
    private javax.swing.JButton btnTransacciones;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbSTitulo1;
    private javax.swing.JLabel lbSTitulo5;
    private javax.swing.JLabel lbSTitulo6;
    private javax.swing.JLabel lbSTitulo7;
    private javax.swing.JLabel lbSTitulo8;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtCantRetirada;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtNumTarjeta;
    private javax.swing.JTextField txtSaldoActual;
    private javax.swing.JTextField txtUltimoAcceso;
    // End of variables declaration//GEN-END:variables

    private void buscarUsuario() {
        if (!txtNumTarjeta.getText().isEmpty()) {
            Usuario usuario = UsuarioLogic.obtener(txtNumTarjeta.getText());
            if (usuario != null) {
                txtNumTarjeta.setText("");
                txtNumTarjeta.setText(usuario.getNumTarjeta());
                txtNumCuenta.setText("");
                txtNumCuenta.setText(usuario.getNumCuenta());
                txtCantRetirada.setText("");
                txtCantRetirada.setText(Integer.toString(usuario.getTotalRetirado()));
                txtSaldoActual.setText("");
                txtSaldoActual.setText(usuario.getSaldo());
                txtUltimoAcceso.setText("");
                txtUltimoAcceso.setText(usuario.getFechaHora_Salida());

            } else {
                JOptionPane.showMessageDialog(null, "El Usuario no existe");
            }
        }
    }

    private void initListeners() {
        txtNumTarjeta.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                if (txtNumTarjeta.getText().equals("Número de Tarjeta")) {
                    txtNumTarjeta.setText("");
                    txtNumTarjeta.setForeground(new Color(0, 8, 66));
                }
            }

            public void focusLost(FocusEvent evt) {
                if (txtNumTarjeta.getText().isEmpty()) {
                    txtNumTarjeta.setText("Número de Tarjeta");
                    txtNumTarjeta.setForeground(new Color(0, 8, 66));
                }
            }
        });

        txtNumCuenta.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                if (txtNumCuenta.getText().equals("Número de Cuenta")) {
                    txtNumCuenta.setText("");
                    txtNumCuenta.setForeground(new Color(0, 8, 66));
                }
            }

            public void focusLost(FocusEvent evt) {
                if (txtNumCuenta.getText().isEmpty()) {
                    txtNumCuenta.setText("Número de Cuenta");
                    txtNumCuenta.setForeground(new Color(0, 8, 66));
                }
            }
        });

        txtCantRetirada.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                if (txtCantRetirada.getText().equals("Cantidad Retirada")) {
                    txtCantRetirada.setText("");
                    txtCantRetirada.setForeground(new Color(0, 8, 66));
                }
            }

            public void focusLost(FocusEvent evt) {
                if (txtCantRetirada.getText().isEmpty()) {
                    txtCantRetirada.setText("Cantidad Retirada");
                    txtCantRetirada.setForeground(new Color(0, 8, 66));
                }
            }
        });

        txtSaldoActual.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                if (txtSaldoActual.getText().equals("Saldo Actual")) {
                    txtSaldoActual.setText("");
                    txtSaldoActual.setForeground(new Color(0, 8, 66));
                }
            }

            public void focusLost(FocusEvent evt) {
                if (txtSaldoActual.getText().isEmpty()) {
                    txtSaldoActual.setText("Saldo Actual");
                    txtSaldoActual.setForeground(new Color(0, 8, 66));
                }
            }
        });

        txtUltimoAcceso.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                if (txtUltimoAcceso.getText().equals("Último Acceso")) {
                    txtUltimoAcceso.setText("");
                    txtUltimoAcceso.setForeground(new Color(0, 8, 66));
                }
            }

            public void focusLost(FocusEvent evt) {
                if (txtUltimoAcceso.getText().isEmpty()) {
                    txtUltimoAcceso.setText("Último Acceso");
                    txtUltimoAcceso.setForeground(new Color(0, 8, 66));
                }
            }
        });
    }
}
