package Interfaz;

import cajero.modelo.Cajero;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import modelo.logic.UsuarioLogic;

/**
 *
 * @author Juan Diaz
 */
public class Depositos_User extends javax.swing.JPanel {

    /**
     * Creates new form Depositos_User
     */
    private Cajero cajero;
    public Map<Integer, Integer> cantidadDeposito = new HashMap<>();

    public Depositos_User() {
        cajero = Cajero.getInstancia();  // Usar la instancia actual
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbValor = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbSTitulo = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbSTitulo2 = new javax.swing.JLabel();
        txtPinUser = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        lbSTitulo3 = new javax.swing.JLabel();
        txtNumCuenta = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnDepositar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbBilletes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadBilletes = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbValor.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbValor.setText("0");
        add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        lbTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbTitulo.setText("Depósito: Q");
        add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lbSTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo.setText("No. Tarjeta");
        add(lbSTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        txtNumTarjeta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNumTarjeta.setForeground(new java.awt.Color(0, 8, 66));
        txtNumTarjeta.setText("Número de Tarjeta");
        txtNumTarjeta.setBorder(null);
        add(txtNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 490, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator1.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 490, 10));

        lbSTitulo2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo2.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo2.setText("PIN");
        add(lbSTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txtPinUser.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtPinUser.setForeground(new java.awt.Color(0, 8, 66));
        txtPinUser.setText("**********");
        txtPinUser.setBorder(null);
        add(txtPinUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 490, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator3.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 490, 10));

        lbSTitulo3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo3.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo3.setText("No. Cuenta");
        add(lbSTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        txtNumCuenta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNumCuenta.setForeground(new java.awt.Color(0, 8, 66));
        txtNumCuenta.setText("Número de Cuenta");
        txtNumCuenta.setBorder(null);
        add(txtNumCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 490, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator4.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 490, 10));

        btnDepositar.setBackground(new java.awt.Color(12, 33, 193));
        btnDepositar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(255, 255, 255));
        btnDepositar.setText("Depositar");
        btnDepositar.setBorderPainted(false);
        btnDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        add(btnDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 130, 30));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Billetes:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, 20));

        cbBilletes.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cbBilletes.setForeground(new java.awt.Color(0, 8, 66));
        cbBilletes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "100", "50", "20", "10", "5", "1" }));
        cbBilletes.setBorder(null);
        cbBilletes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(cbBilletes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 86, 30));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Cantidad:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        txtCantidadBilletes.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtCantidadBilletes.setSelectionColor(new java.awt.Color(12, 33, 193));
        add(txtCantidadBilletes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 132, -1));

        btnAgregar.setBackground(new java.awt.Color(12, 33, 193));
        btnAgregar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        depositarUsuario();
        lbValor.setText(Integer.toString(valorDeposito()));
        cajero.mostrarTotal();

    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarBilletes();
        lbValor.setText(Integer.toString(valorDeposito()));
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JComboBox<String> cbBilletes;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbSTitulo;
    private javax.swing.JLabel lbSTitulo2;
    private javax.swing.JLabel lbSTitulo3;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField txtCantidadBilletes;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtNumTarjeta;
    private javax.swing.JPasswordField txtPinUser;
    // End of variables declaration//GEN-END:variables

    private void depositarUsuario() {
        // Obtener los valores de los campos de texto
        String numTarjeta = txtNumTarjeta.getText();
        String pin = new String(txtPinUser.getPassword());
        String numCuentaDestino = txtNumCuenta.getText();

        // Crear el mapa de billetes
        Map<Integer, Integer> billetes = new HashMap<>();
        try {
            int denominacion = Integer.parseInt((String) cbBilletes.getSelectedItem());
            int cantidadBilletes = Integer.parseInt(txtCantidadBilletes.getText());
            billetes.put(denominacion, cantidadBilletes);

            // Llamar al método depositar
            boolean exito = UsuarioLogic.depositar(numTarjeta, pin, numCuentaDestino, billetes, cajero);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Depósito realizado con éxito.");
                cantidadDeposito.clear();
            } else {
                JOptionPane.showMessageDialog(this, "Error en el depósito. Verifique los datos e intente nuevamente.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores válidos para la denominación y la cantidad de billetes.");
        }
    }

    private void agregarBilletes() {
        int cantidad = Integer.parseInt(txtCantidadBilletes.getText());
        if (cantidad > 0) {
            int denominacion = Integer.parseInt((String) cbBilletes.getSelectedItem());

            // Verifica si la denominación ya existe en el HashMap
            if (cantidadDeposito.containsKey(denominacion)) {
                // Si existe, suma la nueva cantidad a la cantidad existente
                int cantidadExistente = cantidadDeposito.get(denominacion);
                cantidadDeposito.put(denominacion, cantidadExistente + cantidad);
            } else {
                // Si no existe, simplemente agrega la denominación con la cantidad ingresada
                cantidadDeposito.put(denominacion, cantidad);
            }
        } else {
            System.out.println("Ingrese una cantidad válida.");
        }
    }

    private int valorDeposito() {
        int total = 0;
        for (Map.Entry<Integer, Integer> entry : cantidadDeposito.entrySet()) {
            int denominacion = entry.getKey();
            int cantidad = entry.getValue();
            total += cantidad * denominacion;
        }
        return total;
    }
}
