package Interfaz;

/**
 *
 * @author Juan Diaz
 */
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.beans.Transaccion;
import modelo.beans.Usuario;
import modelo.logic.UsuarioLogic;

public class Gestion_User extends javax.swing.JPanel {

    /**
     * Creates new form Gestion_User
     */
    DefaultTableModel tablaTransacciones;
    private Usuario user; //Referencia del usuario

    public Gestion_User(Usuario usuario) {
        initComponents();
        user = usuario;

        tablaTransacciones = new DefaultTableModel();
        String[] titulo = new String[]{"Monto", "Tipo", "Fecha", "Hora"};
        tablaTransacciones.setColumnIdentifiers(titulo);
        tblTransacciones.setModel(tablaTransacciones);
        tblTransacciones.setEnabled(false);

        ejecutarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbSTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransacciones = new javax.swing.JTable();
        lbSTitulo1 = new javax.swing.JLabel();
        lbSTitulo2 = new javax.swing.JLabel();
        txtMontoMaximo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbSTitulo3 = new javax.swing.JLabel();
        txtMontoDisponible = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbSTitulo4 = new javax.swing.JLabel();
        txtSaldoDisponible = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbTitulo.setText("Gestión Cuenta");
        add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lbSTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo.setForeground(new java.awt.Color(0, 8, 66));
        lbSTitulo.setText("Saldo Disponible");
        add(lbSTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        tblTransacciones.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTransacciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 510, 170));

        lbSTitulo1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo1.setForeground(new java.awt.Color(0, 8, 66));
        lbSTitulo1.setText("Últimas Transacciones");
        add(lbSTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        lbSTitulo2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo2.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo2.setText("Monto Máximo Retiro");
        add(lbSTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        txtMontoMaximo.setEditable(false);
        txtMontoMaximo.setBackground(new java.awt.Color(255, 255, 255));
        txtMontoMaximo.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtMontoMaximo.setForeground(new java.awt.Color(0, 8, 66));
        txtMontoMaximo.setBorder(null);
        add(txtMontoMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 160, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator1.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 160, 10));

        lbSTitulo3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo3.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo3.setText("Monto Disponible en el Día");
        add(lbSTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        txtMontoDisponible.setEditable(false);
        txtMontoDisponible.setBackground(new java.awt.Color(255, 255, 255));
        txtMontoDisponible.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtMontoDisponible.setForeground(new java.awt.Color(0, 8, 66));
        txtMontoDisponible.setBorder(null);
        add(txtMontoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 160, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator2.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 160, 10));

        lbSTitulo4.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbSTitulo4.setForeground(new java.awt.Color(153, 153, 153));
        lbSTitulo4.setText("Saldo");
        add(lbSTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        txtSaldoDisponible.setEditable(false);
        txtSaldoDisponible.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldoDisponible.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtSaldoDisponible.setForeground(new java.awt.Color(0, 8, 66));
        txtSaldoDisponible.setBorder(null);
        add(txtSaldoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 160, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator3.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbSTitulo;
    private javax.swing.JLabel lbSTitulo1;
    private javax.swing.JLabel lbSTitulo2;
    private javax.swing.JLabel lbSTitulo3;
    private javax.swing.JLabel lbSTitulo4;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tblTransacciones;
    private javax.swing.JTextField txtMontoDisponible;
    private javax.swing.JTextField txtMontoMaximo;
    private javax.swing.JTextField txtSaldoDisponible;
    // End of variables declaration//GEN-END:variables

    private void ejecutarTodo() {
        ultimasTransacciones();
        saldoDisponible();
        montoDisponible();
        montoMaximoretiro();
    }

    private void agregar_TablaTransacciones(String tipo, int monto, String fecha, String hora) {
        tablaTransacciones.addRow(new Object[]{tipo, monto, fecha, hora});
    }

    private void ultimasTransacciones() {
        List<Transaccion> transacciones = UsuarioLogic.UltimasTransacciones(user);
        if (transacciones != null) {
            for (Transaccion usuario : transacciones) {
                int monto = usuario.getMonto();
                String tipo = usuario.getTipo();
                String fecha = usuario.getFecha();
                String hora = usuario.getHora();

                agregar_TablaTransacciones(tipo, monto, fecha, hora);
            }
        }
    }

    private void montoMaximoretiro() {
        txtMontoMaximo.setText(user.getMonto());
    }

    private void montoDisponible() {
        txtMontoDisponible.setText(user.getMontoDisponible());
    }

    private void saldoDisponible() {
        txtSaldoDisponible.setText(user.getSaldo());
    }
}
