/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author Juan Diaz
 */
public class Log_User extends javax.swing.JPanel {

    /**
     * Creates new form Log_User
     */
    public Log_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbStitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNoTarjeta = new javax.swing.JTextField();
        lbStitulo1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtpinUsuario = new javax.swing.JPasswordField();
        btnCambiarPin = new javax.swing.JButton();
        btnLogUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbTitulo.setText("Usuario");
        add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        lbStitulo.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbStitulo.setForeground(new java.awt.Color(153, 153, 153));
        lbStitulo.setText("No. Tarjeta");
        add(lbStitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator1.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 350, -1));

        txtNoTarjeta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtNoTarjeta.setForeground(new java.awt.Color(0, 8, 66));
        txtNoTarjeta.setText("Número Tarjeta");
        txtNoTarjeta.setBorder(null);
        txtNoTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNoTarjetaMousePressed(evt);
            }
        });
        txtNoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTarjetaActionPerformed(evt);
            }
        });
        add(txtNoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 280, 30));

        lbStitulo1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbStitulo1.setForeground(new java.awt.Color(153, 153, 153));
        lbStitulo1.setText("PIN");
        add(lbStitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 8, 66));
        jSeparator2.setForeground(new java.awt.Color(0, 8, 66));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 350, -1));

        txtpinUsuario.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txtpinUsuario.setForeground(new java.awt.Color(0, 8, 66));
        txtpinUsuario.setText("**********");
        txtpinUsuario.setBorder(null);
        txtpinUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpinUsuarioMousePressed(evt);
            }
        });
        add(txtpinUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        btnCambiarPin.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        btnCambiarPin.setForeground(new java.awt.Color(77, 77, 77));
        btnCambiarPin.setText("Cambiar Pin");
        btnCambiarPin.setBorder(null);
        btnCambiarPin.setBorderPainted(false);
        btnCambiarPin.setContentAreaFilled(false);
        btnCambiarPin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnCambiarPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        btnLogUsuario.setBackground(new java.awt.Color(12, 33, 193));
        btnLogUsuario.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnLogUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnLogUsuario.setText("Entrar");
        btnLogUsuario.setBorderPainted(false);
        btnLogUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnLogUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTarjetaActionPerformed

    private void txtNoTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNoTarjetaMousePressed
        // TODO add your handling code here:
        if (txtNoTarjeta.getText().equals("Número Tarjeta")) {
            txtNoTarjeta.setText("");
            txtNoTarjeta.setForeground(new Color(0, 8, 66));

        }
        if (String.valueOf(txtpinUsuario.getPassword()).isEmpty()) {
            txtpinUsuario.setText("**********");
            txtpinUsuario.setForeground(new Color(0, 8, 66));
        }
    }//GEN-LAST:event_txtNoTarjetaMousePressed

    private void txtpinUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpinUsuarioMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtpinUsuario.getPassword()).equals("**********")) {
            txtpinUsuario.setText("");
            txtpinUsuario.setForeground(new Color(0, 8, 66));
        }
        if (txtNoTarjeta.getText().isEmpty()) {
            txtNoTarjeta.setText("Número Tarjeta");
            txtNoTarjeta.setForeground(new Color(0, 8, 66));
        }
    }//GEN-LAST:event_txtpinUsuarioMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPin;
    private javax.swing.JButton btnLogUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbStitulo;
    private javax.swing.JLabel lbStitulo1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtNoTarjeta;
    private javax.swing.JPasswordField txtpinUsuario;
    // End of variables declaration//GEN-END:variables
}
