package Interfaz;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Juan Diaz
 */
public class Panel_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Admin
     */
    public Panel_Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tools_Admin = new javax.swing.JPanel();
        btnManejoUsuarios = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        Contenido_Admin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tools_Admin.setBackground(new java.awt.Color(0, 8, 66));
        Tools_Admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManejoUsuarios.setText("Manejo Usuarios");
        btnManejoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManejoUsuariosActionPerformed(evt);
            }
        });
        Tools_Admin.add(btnManejoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jButton2.setText("jButton2");
        Tools_Admin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        Tools_Admin.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        getContentPane().add(Tools_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 220, 540));

        Contenido_Admin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Contenido_AdminLayout = new javax.swing.GroupLayout(Contenido_Admin);
        Contenido_Admin.setLayout(Contenido_AdminLayout);
        Contenido_AdminLayout.setHorizontalGroup(
            Contenido_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        Contenido_AdminLayout.setVerticalGroup(
            Contenido_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Contenido_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void CambioPanel(JPanel p) {
        p.setSize(650, 550);
        p.setLocation(0, 0);

        Contenido_Admin.removeAll();
        Contenido_Admin.add(p, BorderLayout.CENTER);
        Contenido_Admin.revalidate();
        Contenido_Admin.repaint();
    }
    private void btnManejoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManejoUsuariosActionPerformed
        // TODO add your handling code here:
        Reg_User regUser = new Reg_User();
        CambioPanel(regUser);
    }//GEN-LAST:event_btnManejoUsuariosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Cierra el Panel_Admin
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido_Admin;
    private javax.swing.JPanel Tools_Admin;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnManejoUsuarios;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
