/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import modelo.beans.Usuario;

/**
 *
 * @author Juan Diaz
 */
public class Panel_User extends javax.swing.JFrame {

    /**
     * Creates new form Panel_User
     */
    public Panel_User(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        lbTitulo.setText("Bienvenido "+usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tools_User = new javax.swing.JPanel();
        Contenido_User = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tools_User.setBackground(new java.awt.Color(0, 8, 66));

        javax.swing.GroupLayout Tools_UserLayout = new javax.swing.GroupLayout(Tools_User);
        Tools_User.setLayout(Tools_UserLayout);
        Tools_UserLayout.setHorizontalGroup(
            Tools_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        Tools_UserLayout.setVerticalGroup(
            Tools_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Tools_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 220, 540));

        Contenido_User.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        lbTitulo.setText("Nombre");

        javax.swing.GroupLayout Contenido_UserLayout = new javax.swing.GroupLayout(Contenido_User);
        Contenido_User.setLayout(Contenido_UserLayout);
        Contenido_UserLayout.setHorizontalGroup(
            Contenido_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenido_UserLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(lbTitulo)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        Contenido_UserLayout.setVerticalGroup(
            Contenido_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenido_UserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbTitulo)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        getContentPane().add(Contenido_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_User(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido_User;
    private javax.swing.JPanel Tools_User;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
